Document: pobshare
Title: Debian pobshare Manual
Author: <insert document author here>
Abstract: This manual describes what pobshare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pobshare/pobshare.sgml.gz

Format: postscript
Files: /usr/share/doc/pobshare/pobshare.ps.gz

Format: text
Files: /usr/share/doc/pobshare/pobshare.text.gz

Format: HTML
Index: /usr/share/doc/pobshare/html/index.html
Files: /usr/share/doc/pobshare/html/*.html
